### ISSUE TITLE
builds/build_logs: unable to see logs

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#1]
**To Reproduce**
1. go to some project
2. click "Trigger Build"
3. click "<-" button (to get back to builds list)
4. click started build
5. logs will not be displayed:
![image](https://user-images.githubusercontent.com/73652197/125166863-f7e49580-e19d-11eb-920c-952c727e2ff3.png)

**Comment by paladium** [comment]
Hi, can you please specify the project you are trying to build I think it might be related in general to the same problem of the uppercase repository name?

**Comment by gucio321** [comment]
I think it happens in any project, I tested two.
e.g.: gucio321/tic-tac-go
build link: https://console.nativeci.io/project/98159e2c-8036-4377-a499-d3e9513446fb/builds/3d68670b-def2-4408-9070-478bffb9c012
![image](https://user-images.githubusercontent.com/73652197/125167838-d043fc00-e1a2-11eb-88bb-02d7c0506198.png)

**Comment by paladium** [comment]
I think I know the problem, I tried using new experimental web streaming api which might not be fully supported in all browsers, will use old string copying to avoid this issue.

**Comment by paladium** [comment]
Should work now, could you try to build your project?

**Comment by gucio321** [comment]
work, thanks
