### ISSUE TITLE
getting linter timeout

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#10]
Hi,
I'm getting `Killed` signal from linter run
![image](https://user-images.githubusercontent.com/73652197/125670760-875973a7-ae5a-4404-b438-d2c45b32fee6.png)

**Comment by paladium** [comment]
Hm, i think it might be related to overall limits on cpu and ram for builds. Maybe there is a way to limit golangci-lint inner limits?

**Comment by gucio321** [comment]
not sure if golangci-lint can  do that itself, but you can use `cpulimit` to limit cpu usage: https://www.tecmint.com/limit-cpu-usage-of-a-process-in-linux-with-cpulimit-tool/
```console
cpulimit --limit=15 golangci-lint run ./...
```
and `ulimit` for memory

**Comment by paladium** [comment]
Yes that exactly what I need for that i will install it and run some tests,
thanks.

**Comment by paladium** [comment]
@gucio321 could be related to ram limits on #18, please try to build again.
