### ISSUE TITLE
[bug]: unable to create new project

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#14]
### Please ensure, you completed the following steps

- [X] I searched for the similar issue.

### Build/Project URL

no project url

### GitHub project

gucio321/ttg-giu

### What happend?

when I click 
![image](https://user-images.githubusercontent.com/73652197/126065110-938f8790-371b-4400-bb7f-bab2de234c13.png)
button no project is created

### To reproduce

1. go do dashboard
2. click new
3. complete wizzard
4. click create
5. you'll see a message about project created, but no project will be created

### What browsers are you seeing the problem on?

Firefox

**Comment by paladium** [comment]
I am looking at the logs, for some reason frontend sent the number for the build envs values, I will add a conversion into string mandatory to avoid json decoding issue.

**Comment by paladium** [comment]
Please try to refresh the page and try again.

**Comment by gucio321** [comment]
sadly still unable to create project

**Comment by paladium** [comment]
Please try to refresh using shift+f5, which will clear local cache

**Comment by gucio321** [comment]
okey, it works now, thx
