### ISSUE TITLE
[feature]: report bug button

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#15]
### Please ensure, you completed the following steps

- [X] I searched for the similar issue.

### Describtion

I'd suggest to add "Report Bug" button linking to this repo somewhere in the app interface.

**Comment by paladium** [comment]
Good idea, what do you think about placing it at the bottom like websites do with that chat button?

**Comment by gucio321** [comment]
>  ![image](https://user-images.githubusercontent.com/73652197/126073341-731b8764-60ec-4a5b-81de-3bf383c69f3f.png)
oh, i missed the label in #12 :grinning:

**Comment by paladium** [comment]
Yeah I am also new to these GitHub features, still figuring out the best workflow :)

**Comment by paladium** [comment]
I guess with assigning lables it would be easier to group tasks

**Comment by gucio321** [comment]
okey, opened a PR (#16)

**Comment by gucio321** [comment]
> Good idea, what do you think about placing it at the bottom like websites do with that chat button?

or maybe in help menu like in some desktop apps?

**Comment by paladium** [comment]
Like besides Dashboard button?

**Comment by gucio321** [comment]
not sure if it is so important feature.

![image](https://user-images.githubusercontent.com/73652197/126074127-44a3d183-aca6-44d7-8ae1-6bd7317661cc.png)

maybe clicking on help button should open the same menu like on user icon and this menu should contain two items:
- about (link to help page)
- o report bug (link to this repo

**Comment by paladium** [comment]
Yeah that will work, okay adding that to my todo list :)

**Comment by paladium** [comment]
@gucio321 the new dropdown is out.

**Comment by gucio321** [comment]
okey, thanx
