### ISSUE TITLE
[feature]: specify linter version

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#17]
### Please ensure, you completed the following steps

- [X] I searched for the similar issue.

### Describtion

you're downloading the latest golangci-lint version, but some projects may want to use some older versions.
it should be possible to select used version. e.g. a dropdown in settings (with values basing on release names on gh). default should be `latest`

[golangci-lint github page](https://github.com/golangci/golangci-lint)

**Comment by paladium** [comment]
Good point, going to my todo list, will make a new endpoint to retrieve linter versions from github API for releases and display it as a dropdown for the user inside of build settings like LINTER_VERSION.

**Comment by paladium** [comment]
@gucio321 the feature is live, you can go to settings and in build envs choose LINTER_VERSION, a list of options will be loaded from golangci-lint tags

**Comment by gucio321** [comment]
hmm, why not to put it in `Linter settings` section? I don't think it is very intuitive way to set it.

**Comment by paladium** [comment]
Yeah was thinking as well about that )

**Comment by paladium** [comment]
@gucio321 moved to Linter settings section

**Comment by gucio321** [comment]
cool, thanx
