### ISSUE TITLE
[bug]: unable to complete build

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#18]
### Please ensure, you completed the following steps

- [X] I searched for the similar issue.

### Build/Project URL

https://console.nativeci.io/project/9a212972-10bd-4c1f-b594-8a9cd59c32ca/builds/9e1578cc-a35e-45ec-95df-ff25db82696d

### GitHub project

gucio321/HellSpawner

### What happend?

build hangs up at build step
![image](https://user-images.githubusercontent.com/73652197/126076321-f07aa602-ee86-4ccc-bd24-21c5b9535e4f.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by paladium** [comment]
Hm what happens when you refresh page is the build failed?

**Comment by gucio321** [comment]
what do you mean? the build isn't failed yet, it just hanged up at b`go build` step

**Comment by paladium** [comment]
How long has it been hanging for?

**Comment by gucio321** [comment]
maybe about 10 min... last log is from 17:06, not sure what is current server time.

**Comment by paladium** [comment]
The sever time is +4 gmt, okay I will investigate what made the build fail, I think there was a similar issue previously maybe it is the same bug that I have not solved yet

**Comment by paladium** [comment]
I looked into logs, seems like the build was taking long time due to cpu + ram limits and eventually it was killed by the docker for going over limits:
```
23:33:50 # github.com/ianling/imgui-go
23:33:50 g++: fatal error: Killed signal terminated program cc1plus
23:33:51 compilation terminated.
23:33:51
```
And seems like the build finished only after a few hours, when you compile the application on your computer, how much time does it take?

**Comment by paladium** [comment]
@gucio321 I have added a feature to enable/disable build log sharing, currently all build logs are private, meaning only you can see them, but when you want to share the link to the build logs, please go to settings and enable: Public builds option.

**Comment by gucio321** [comment]
> And seems like the build finished only after a few hours, when you compile the application on your computer, how much time does it take?

okey, go needs to compile imgui-go so it takes some time but usually build finishes after a few minutes

> @gucio321 I have added a feature to enable/disable build log sharing, currently all build logs are private, meaning only you can see them, but when you want to share the link to the build logs, please go to settings and enable: Public builds option.

hmm, maybe each build could have the button `share` which will generate/show public build url?

**Comment by paladium** [comment]
> > And seems like the build finished only after a few hours, when you compile the application on your computer, how much time does it take?
> 
> okey, go needs to compile imgui-go so it takes some time but usually build finishes after a few minutes
> 
> > @gucio321 I have added a feature to enable/disable build log sharing, currently all build logs are private, meaning only you can see them, but when you want to share the link to the build logs, please go to settings and enable: Public builds option.
> 
> hmm, maybe each build could have the button `share` which will generate/show public build url?

@gucio321 share link for the build is working. Could you please configure the public builds for that project?

**Comment by gucio321** [comment]
https://console.nativeci.io/project/9a212972-10bd-4c1f-b594-8a9cd59c32ca/builds/a64cbf91-e686-48b5-9c00-dcdeca7f88d2
here is a link to example build log.

**Comment by paladium** [comment]
@gucio321 the problem is most likely related to little memory available to each build, currently 1gb of ram is available to each build, let me increase that limit to 2gb and try to build the project again to see if it builds successfully?
