### ISSUE TITLE
[bug]: unable to see logs

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#19]
### Please ensure, you completed the following steps

- [X] I searched for the similar issue.

### Build/Project URL

doesn't metter

### GitHub project

doesn't metter

### What happend?

anyone (including myself) is unable to see build logs when `Public builds` is false.
btw I'd suggest another way for sharing build logs:
build log panel could contain `Share` button. when you click the button CI could generate a build url and user could copy an use it. or maybe any other link should be generated. just if someone access build link app could check if sharing is on.

### To reproduce

1. turn off `public builds` option
2. click `save in settings
3. you'll not see any logs

### What browsers are you seeing the problem on?

Firefox

**Comment by paladium** [comment]
Interesting, maybe I forgot to check that flow. Yes I was thinking about making a share button that would be more intuitive

**Comment by paladium** [comment]
@gucio321 the issue with build logs should be fixed now
