### ISSUE TITLE
[feature]: Allow to run vnc server for GUI apps inside the container

### ISSUE THREAD

**Issue by paladium** [NativeCI/Issues#21]
### Please ensure, you completed the following steps

- [X] I searched for the similar issue.

### Description

@gucio321 i noticed that you tried to run OpenDiablo2 project and it gave the following error:
```
2021/07/21 19:14:11 PlatformError: X11: The DISPLAY environment variable is missing
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0x0, 0x10006)
        /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:174 +0x225

```
I searched around and found it is possible to run vnc server inside of the container and allow the user to connect to it from outside (even in the browser), for example running firefox in container:
```
FROM ubuntu:latest
RUN apt-get update && apt-get install -y firefox x11vnc xvfb
RUN echo "exec firefox" > ~/.xinitrc && chmod +x ~/.xinitrc
CMD ["v11vnc", "-create", "-forever"]
```
What do you think about this feature, is it something worth pursuing?

**Comment by paladium** [comment]
Good will be curious how it will all come together, especially since I am so used to web + API apps

**Comment by gucio321** [comment]
btw, i can probably run my tests with this command:
xvfb-run --auto-servernum go test -v -race ./...

**Comment by paladium** [comment]
@gucio321 great, that can work for now, i will add that to documentation as well, will postpone the vnc feature for now.
