### ISSUE TITLE
getting goos-related build error

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#3]
Hi there,
I'm trying to run tests on [gucio321/OpenDiablo2](https://github.com/opendiablo2/opendiablo2) project, but I'm getting the following error:
```console
16:14:03 package command-line-arguments
16:14:03        imports github.com/OpenDiablo2/OpenDiablo2/d2app
16:14:03        imports github.com/OpenDiablo2/OpenDiablo2/d2common/d2util
16:14:03        imports github.com/hajimehoshi/ebiten/v2
16:14:03        imports github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw
16:14:03        imports github.com/hajimehoshi/ebiten/v2/internal/devicescale
16:14:03        imports github.com/hajimehoshi/ebiten/v2/internal/glfw
16:14:03        imports github.com/go-gl/glfw/v3.3/glfw: build constraints exclude all Go files in /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2
16:14:03 
```

the project build fine on my linux machine
what GOOS and GOARCH does the CI use?

**Comment by paladium** [comment]
Interesting, currently no values are set and defaults are used. I could add additional flags to customize build environment variables, including GOOS and GOARCH.

**Comment by paladium** [comment]
Additional feature I can add it basically autocomplete those values for go projects, like if you choose GOOS, it will basically show you all possible values for GOOS that you can choose or can type your own.

**Comment by paladium** [comment]
What do you think would be the easiest way for you to manage those settings?

**Comment by gucio321** [comment]
maybe a dropdown?

**Comment by gucio321** [comment]
hmm, @paladium I'm unable to access console on this project (OpenDiablo2) maybe related with #1?
![image](https://user-images.githubusercontent.com/73652197/125175666-ea470400-e1cd-11eb-9932-167b9849136e.png)

**Comment by paladium** [comment]
Yes so as you can see from the top the application is currently down and not deployed, meaning no logs will be available.

**Comment by paladium** [comment]
As well as the attach will also fail. Probably will be a good idea to add a message to show that the application is not deployed.

**Comment by paladium** [comment]
> maybe a dropdown?

Yeah I agree basically a dropdown with autocomplete, I will let you know once it is done

**Comment by paladium** [comment]
@gucio321 I have added build environment variables in the settings tab, please try to set values for GOOS and GOARCH matching your local settings and see if that solves the build problem.

**Comment by paladium** [comment]
> hmm, @paladium I'm unable to access console on this project (OpenDiablo2) maybe related with #1?
> ![image](https://user-images.githubusercontent.com/73652197/125175666-ea470400-e1cd-11eb-9932-167b9849136e.png)

@gucio321 now if the application is not deployed, the appropriate buttons will be disabled and you can also track if the project is currently deployed or not

**Comment by gucio321** [comment]
okey, everything works, buttons are disabled, global variables can be set

sadly it doesn't solve my problem :sad:  I still get ` build constraints exclude all Go files in /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2` error. It is related with go-gl/glfw module. I'll try to figure it out

**Comment by paladium** [comment]
Could it be related because CGO_ENABLED is set to 0 by default?

**Comment by gucio321** [comment]
yep, it was that, thank you
