### ISSUE TITLE
feature: cancel build

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#4]
sometimes build hangs up and it should be possible to cancel it (like GH workflow).

**Comment by paladium** [comment]
Sounds like a good idea to me, and the cancelled build will have the status cancelled.

**Comment by paladium** [comment]
@gucio321 FYI I am still testing the cancel build feature, the button might be there but it is still not functional.

**Comment by paladium** [comment]
@gucio321 the feature is live, please try to use it and provide your feedback

**Comment by gucio321** [comment]
okey, feature works, but shouldn't be `cancelled` status reported somewhere?
![image](https://user-images.githubusercontent.com/73652197/126075529-8d9246cd-58c2-45bb-8d6a-5ede2862fc31.png)

**Comment by paladium** [comment]
It actually does just need to press shift+f5, chrome cache for some reason does not see new build versions by webpack

**Comment by gucio321** [comment]
> It actually does just need to press shift+f5, chrome cache for some reason does not see new build versions by webpack

im on firefox atm, hot to hard-refresh here :grinning:

**Comment by paladium** [comment]
Yeah, unfortunately, you could try these steps though:
```
Open the developer toolbox (Ctrl+Shift+I or Cmd+Opt+I on Mac).
Click the settings button (near the top right).
Scroll down to the Advanced settings on the bottom right.
Check the option "Disable Cache (when toolbox is open)".
Refresh the page.
```

**Comment by gucio321** [comment]
okey, i think `f5` was enough thhis time.
![image](https://user-images.githubusercontent.com/73652197/126076404-a864f811-4aca-4b98-bcc3-b00d82ed07e3.png)
