### ISSUE TITLE
build hangs up

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#5]
I have again the issue, I reported on go forum:
OpenDiablo2/OpenDiablo2 projects hangs up:
![image](https://user-images.githubusercontent.com/73652197/125510417-3f97ecd6-1a95-4e12-bcac-73cb7eb1123f.png)

**Comment by paladium** [comment]
Hm i will look into it, I don't think it is caused by the same reason before - lowercase repository name, so it must be something else.

**Comment by paladium** [comment]
I actually looked into logs and everything is fine, the build failed with the following error:
```
15:11:50 	imports github.com/OpenDiablo2/OpenDiablo2/d2app
15:11:50 	imports github.com/OpenDiablo2/OpenDiablo2/d2common/d2util
15:11:50 	imports github.com/hajimehoshi/ebiten/v2
15:11:50 	imports github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw
15:11:50 	imports github.com/hajimehoshi/ebiten/v2/internal/devicescale
15:11:50 	imports github.com/hajimehoshi/ebiten/v2/internal/glfw
15:11:50 	imports github.com/go-gl/glfw/v3.3/glfw: build constraints exclude all Go files in /go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2
```
Could you check the build for that project to verify whether it has completed?

**Comment by gucio321** [comment]
sure, it is because I removed my project instance and created it again, it could have been a one-time error, I'll check it again.

**Comment by gucio321** [comment]
btw, could you add `CGO_ENABLED` to build env variables

**Comment by gucio321** [comment]
okey, doesn't happen anymore
