### ISSUE TITLE
add CGO_ENABLED to build env variables dropdown

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#7]
var name: `CGO_ENABLED`
possible values:
- `1` (enabled)
- `0` (disabled)

**Comment by paladium** [comment]
Sure no problem

**Comment by paladium** [comment]
Done, should now be set for new projects to zero and you can also edit it for existing projects with dropdown.

**Comment by gucio321** [comment]
> Done, should now be set for new projects to zero 

not sure, but default set for `go env` is 1 (at least to me)

**Comment by paladium** [comment]
Hmm I am actually setting it to zero by default because it results in
faster and smaller binaries

**Comment by gucio321** [comment]
fair enough

**Comment by gucio321** [comment]
but it may be a bit confusing for some people, because error message caused by CGO_ENABLED=0 isn't so obvious, maybe add something to settings?
like: "my project uses CGO" switcher

**Comment by paladium** [comment]
Yeah good point, I will think how to add it, maybe try to put it into a
drop down where the build env value is chosen - choose 0 if your project
doesn't depend on its value and 1 if your project requires c language
Integration
