### ISSUE TITLE
status: `failed`, but no errors

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#8]
Hi,
could you look at this logs: https://console.nativeci.io/project/36033767-64af-4690-ae8b-b080cd607b4f/builds/cf70baab-5f25-4159-bc8e-5444fcd49924
I don't see any error message, but build status is `failed`

**Comment by gucio321** [comment]
![image](https://user-images.githubusercontent.com/73652197/125666925-aec8eb1d-c0b7-4078-92b4-e3a120f4ec00.png)
everything is passed

**Comment by paladium** [comment]
Sorry my mistake, I looked into your logs and few tests have failed, however they were not reported individually as that is why you cannot see them fail. You can actually download the raw log as see for yourself:
```
17:28:18 nativeci:test {"Time":"2021-07-14T17:28:18.116788261Z","Action":"fail","Package":"github.com/OpenDiablo2/OpenDiablo2/d2core/d2stats/diablo2stats","Elapsed":0.033}
```

**Comment by paladium** [comment]
I will change my regex for test reporting and will let you know :)

**Comment by paladium** [comment]
@gucio321 the issue should be fixed now, try to build the project one more time

**Comment by paladium** [comment]
@gucio321 please let me know if the build errors show up in the tests tab?
