### ISSUE TITLE
use `Attach` if tests fails

### ISSUE THREAD

**Issue by gucio321** [NativeCI/Issues#9]
Hi,
It might be useful to use `Attach` button if `go test [...]` command fails, You may want to check `What exactly failed` and try some fixes.

**Comment by gucio321** [comment]
maybe something like that:
if build command returns non-zer exit code, set build status to `failed` and disable all buttons
if test command or linter returns non-0 status, return `failed` but enable attach button.

**Comment by paladium** [comment]
The problem with that solution is that even if you attach to the container and edit some files, there will be no easy way for you to commit those changes back to github.
Another problem is that, the image is not fully built at the moment it failed. It is possible to override exit codes and basically pipe them to the application by a different means, but another issue is that how would the user know what he is attaching to - the running application or failed build.

**Comment by gucio321** [comment]
> The problem with that solution is that even if you attach to the container and edit some files, there will be no easy way for you to commit those changes back to github.

not sure, but iirc [circleCI](https://circleci.com) project can be set up by using its api, the CI creates a new branch in your repo an commits (using your username) config file, however it isn't really necessary, you may just want to check whats going wrong and fix it using your local machine.

> but another issue is that how would the user know what he is attaching to - the running application or failed build.

hmm, thats serious issue, maybe attach buttons should be placed between each build...

btw, could you make it a Discussion (not issue)
